<a href="https://colab.research.google.com/github/osergioribeirof/Python/blob/main/DRE__E_Balan%C3%A7o_Patrimonial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Biblioteca

In [4]:
pip install yfinance

Collecting yfinance
  Downloading yfinance-0.2.65-py2.py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: pandas>=1.3.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from yfinance) (2.3.2)
Requirement already satisfied: numpy>=1.16.5 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from yfinance) (2.3.3)
Requirement already satisfied: requests>=2.31 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from yfinance) (2.32.5)
Collecting multitasking>=0.0.7 (from yfinance)
  Downloading multitasking-0.0.12.tar.gz (19 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: platformdirs>=2.0.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from yfinance) (4.4.0)
Requirement already satisfied: pytz>=2022.5 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from yfinance) (2025.2)
Collecting frozendict>=2.3.4 (from yfinance)
  Downloading frozendict-2.4.6-py313-none-any.whl.metadata (23 kB)
Collecting peewee>=3.16.2 (from yfinance)
  Downloading peewee-3.18.2.tar.gz (949 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 949.2/949.2 kB 4.3 MB/s  0:00:00eta 0:00:01
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting beautifulsoup4>=4.11.1 (from yfinance)
  Downloading beautifulsoup4-4.13.5-py3-none-any.whl.metadata (3.8 kB)
Collecting curl_cffi>=0.7 (from yfinance)
  Downloading curl_cffi-0.13.0-cp39-abi3-macosx_11_0_arm64.whl.metadata (13 kB)
Collecting protobuf>=3.19.0 (from yfinance)
  Downloading protobuf-6.32.1-cp39-abi3-macosx_10_9_universal2.whl.metadata (593 bytes)
Collecting websockets>=13.0 (from yfinance)
  Downloading websockets-15.0.1-cp313-cp313-macosx_11_0_arm64.whl.metadata (6.8 kB)
Collecting soupsieve>1.2 (from beautifulsoup4>=4.11.1->yfinance)
  Downloading soupsieve-2.8-py3-none-any.whl.metadata (4.6 kB)
Collecting typing-extensions>=4.0.0 (from beautifulsoup4>=4.11.1->yfinance)
  Downloading typing_extensions-4.15.0-py3-none-any.whl.metadata (3.3 kB)
Collecting cffi>=1.12.0 (from curl_cffi>=0.7->yfinance)
  Downloading cffi-2.0.0-cp313-cp313-macosx_11_0_arm64.whl.metadata (2.6 kB)
Requirement already satisfied: certifi>=2024.2.2 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from curl_cffi>=0.7->yfinance) (2025.8.3)
Collecting pycparser (from cffi>=1.12.0->curl_cffi>=0.7->yfinance)
  Downloading pycparser-2.23-py3-none-any.whl.metadata (993 bytes)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/sergioribeiromacbook/Library/Python/3.13/lib/python/site-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pandas>=1.3.0->yfinance) (2025.2)
Requirement already satisfied: six>=1.5 in /Users/sergioribeiromacbook/Library/Python/3.13/lib/python/site-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from requests>=2.31->yfinance) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from requests>=2.31->yfinance) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from requests>=2.31->yfinance) (2.5.0)
Downloading yfinance-0.2.65-py2.py3-none-any.whl (119 kB)
Downloading beautifulsoup4-4.13.5-py3-none-any.whl (105 kB)
Downloading curl_cffi-0.13.0-cp39-abi3-macosx_11_0_arm64.whl (3.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.0/3.0 MB 4.4 MB/s  0:00:00 eta 0:00:01
Downloading cffi-2.0.0-cp313-cp313-macosx_11_0_arm64.whl (181 kB)
Downloading frozendict-2.4.6-py313-none-any.whl (16 kB)
Downloading protobuf-6.32.1-cp39-abi3-macosx_10_9_universal2.whl (426 kB)
Downloading soupsieve-2.8-py3-none-any.whl (36 kB)
Downloading typing_extensions-4.15.0-py3-none-any.whl (44 kB)
Downloading websockets-15.0.1-cp313-cp313-macosx_11_0_arm64.whl (173 kB)
Downloading pycparser-2.23-py3-none-any.whl (118 kB)
Building wheels for collected packages: multitasking, peewee
  Building wheel for multitasking (pyproject.toml) ... done
  Created wheel for multitasking: filename=multitasking-0.0.12-py3-none-any.whl size=15636 sha256=250bc4b178cb16831b3169ea46cbc7262a1af48a55cf19a89c41916730aa68b1
  Stored in directory: /Users/sergioribeiromacbook/Library/Caches/pip/wheels/1e/df/0f/e2bbb22d689b30c681feb5410ab64a2523437b34c8ecfc6476
  Building wheel for peewee (pyproject.toml) ... done
  Created wheel for peewee: filename=peewee-3.18.2-cp313-cp313-macosx_10_13_universal2.whl size=433953 sha256=6ae76f4cb7e0aa81f8e1f8dc19e754a52890458e9cd05909e4e3296f6a45d1c6
  Stored in directory: /Users/sergioribeiromacbook/Library/Caches/pip/wheels/1c/48/cc/00b7d0e7defa21a58915654917c89eaedd32a6e614d8e4ad92
Successfully built multitasking peewee
Installing collected packages: peewee, multitasking, websockets, typing-extensions, soupsieve, pycparser, protobuf, frozendict, cffi, beautifulsoup4, curl_cffi, yfinance
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12/12 [yfinance]/12 [curl_cffi]
Successfully installed beautifulsoup4-4.13.5 cffi-2.0.0 curl_cffi-0.13.0 frozendict-2.4.6 multitasking-0.0.12 peewee-3.18.2 protobuf-6.32.1 pycparser-2.23 soupsieve-2.8 typing-extensions-4.15.0 websockets-15.0.1 yfinance-0.2.65
Note: you may need to restart the kernel to use updated packages.

In [6]:
import numpy as np
import pandas as pd
import yfinance as yf
import plotly.graph_objects as go
from plotly.subplots import make_subplots

### Ativo

In [7]:
ativo = yf.Ticker('VALE3.SA')

### Dados Trimestre

In [8]:
dre = ativo.get_financials(freq='quarterly')
dre

,2025-06-30,2025-03-31,2024-12-31,2024-09-30,2024-06-30,2024-03-31,2023-12-31
TaxEffectOfUnusualItems,1.139000e+08,1.583456e+06,-1.060544e+08,8.661826e+07,6.664000e+07,NaN,NaN
TaxRateForCalcs,3.400000e-01,3.166910e-01,3.218600e-02,1.232120e-01,3.400000e-01,NaN,NaN
NormalizedEBITDA,2.895000e+09,3.027000e+09,3.704000e+09,3.044000e+09,3.776000e+09,NaN,NaN
TotalUnusualItems,3.350000e+08,5.000000e+06,-3.295000e+09,7.030000e+08,1.960000e+08,NaN,NaN
TotalUnusualItemsExcludingGoodwill,3.350000e+08,5.000000e+06,-3.295000e+09,7.030000e+08,1.960000e+08,NaN,NaN
NetIncomeFromContinuingOperationNetMinorityInterest,2.117000e+09,1.394000e+09,-6.940000e+08,2.412000e+09,2.769000e+09,NaN,NaN
ReconciledDepreciation,7.800000e+08,7.040000e+08,8.020000e+08,7.480000e+08,7.930000e+08,NaN,NaN
ReconciledCostOfRevenue,5.312000e+09,4.771000e+09,5.489000e+09,5.547000e+09,5.565000e+09,NaN,NaN
EBITDA,3.230000e+09,3.032000e+09,4.090000e+08,3.747000e+09,3.972000e+09,NaN,NaN
EBIT,2.450000e+09,2.328000e+09,-3.930000e+08,2.999000e+09,3.179000e+09,NaN,NaN
NetInterestIncome,-4.090000e+08,-3.260000e+08,-6.160000e+08,-1.880000e+08,-5.280000e+08,NaN,NaN
InterestExpense,3.470000e+08,2.850000e+08,5.080000e+08,2.720000e+08,4.440000e+08,NaN,NaN
InterestIncome,1.120000e+08,5.600000e+07,2.000000e+07,4.300000e+07,7.800000e+07,NaN,NaN
NormalizedIncome,1.895900e+09,1.390583e+09,2.494946e+09,1.795618e+09,2.639640e+09,NaN,NaN
NetIncomeFromContinuingAndDiscontinuedOperation,2.117000e+09,1.394000e+09,-6.940000e+08,2.412000e+09,2.769000e+09,NaN,NaN
TotalExpenses,6.559000e+09,5.814000e+09,7.183000e+09,6.767000e+09,6.965000e+09,NaN,NaN
TotalOperatingIncomeAsReported,2.004000e+09,1.799000e+09,7.900000e+08,3.675000e+09,3.875000e+09,NaN,NaN
DilutedAverageShares,4.234000e+09,4.273772e+09,NaN,4.274508e+09,4.260000e+09,4.289631e+09,NaN
BasicAverageShares,4.234000e+09,4.268759e+09,NaN,4.269495e+09,4.260000e+09,4.285865e+09,NaN
DilutedEPS,5.000000e-01,3.300000e-01,NaN,5.600000e-01,6.500000e-01,3.900000e-01,NaN
BasicEPS,5.000000e-01,3.300000e-01,NaN,5.600000e-01,6.500000e-01,3.900000e-01,NaN
DilutedNIAvailtoComStockholders,2.117000e+09,1.394000e+09,-6.940000e+08,2.412000e+09,2.769000e+09,NaN,NaN
NetIncomeCommonStockholders,2.117000e+09,1.394000e+09,-6.940000e+08,2.412000e+09,2.769000e+09,NaN,NaN
NetIncome,2.117000e+09,1.394000e+09,-6.940000e+08,2.412000e+09,2.769000e+09,NaN,NaN
MinorityInterests,-1.800000e+07,-2.000000e+06,1.780000e+08,2.100000e+07,0.000000e+00,NaN,NaN
NetIncomeIncludingNoncontrollingInterests,2.135000e+09,1.396000e+09,-8.720000e+08,2.391000e+09,2.769000e+09,NaN,NaN
NetIncomeDiscontinuousOperations,NaN,NaN,NaN,NaN,NaN,NaN,0.0
NetIncomeContinuousOperations,2.135000e+09,1.396000e+09,-8.720000e+08,2.391000e+09,2.769000e+09,NaN,NaN
TaxProvision,-3.200000e+07,6.470000e+08,-2.900000e+07,3.360000e+08,-3.400000e+07,NaN,NaN
PretaxIncome,2.103000e+09,2.043000e+09,-9.010000e+08,2.727000e+09,2.735000e+09,NaN,NaN
OtherIncomeExpense,2.670000e+08,6.400000e+07,-3.226000e+09,1.290000e+08,3.080000e+08,NaN,NaN
SpecialIncomeCharges,-2.410000e+08,-5.060000e+08,-2.101000e+09,8.390000e+08,9.200000e+08,NaN,NaN
GainOnSaleOfBusiness,NaN,NaN,NaN,NaN,1.059000e+09,NaN,NaN
OtherSpecialCharges,1.090000e+08,2.530000e+08,2.540000e+08,3.050000e+08,9.000000e+07,NaN,NaN
WriteOff,1.320000e+08,2.530000e+08,NaN,NaN,-1.010000e+09,6.000000e+06,NaN
ImpairmentOfCapitalAssets,1.320000e+08,NaN,1.847000e+09,-1.144000e+09,-1.010000e+09,6.000000e+06,NaN
EarningsFromEquityInterest,-6.800000e+07,5.900000e+07,6.900000e+07,-5.740000e+08,1.120000e+08,NaN,NaN
GainOnSaleOfSecurity,5.760000e+08,5.110000e+08,-1.194000e+09,-1.360000e+08,-7.240000e+08,NaN,NaN
NetNonOperatingInterestIncomeExpense,-4.090000e+08,-3.260000e+08,-6.160000e+08,-1.880000e+08,-5.280000e+08,NaN,NaN
TotalOtherFinanceCost,1.740000e+08,9.700000e+07,1.280000e+08,-4.100000e+07,1.620000e+08,NaN,NaN
InterestExpenseNonOperating,3.470000e+08,2.850000e+08,5.080000e+08,2.720000e+08,4.440000e+08,NaN,NaN
InterestIncomeNonOperating,1.120000e+08,5.600000e+07,2.000000e+07,4.300000e+07,7.800000e+07,NaN,NaN
OperatingIncome,2.245000e+09,2.305000e+09,2.941000e+09,2.786000e+09,2.955000e+09,NaN,NaN
OperatingExpense,4.740000e+08,3.630000e+08,9.150000e+08,4.860000e+08,6.160000e+08,NaN,NaN
OtherOperatingExpenses,1.840000e+08,9.500000e+07,4.560000e+08,1.550000e+08,2.900000e+08,NaN,NaN
DepreciationAmortizationDepletionIncomeStatement,7.000000e+06,2.400000e+07,2.300000e+07,1.400000e+07,9.000000e+06,NaN,NaN
DepreciationAndAmortizationInIncomeStatement,7.000000e+06,2.400000e+07,2.300000e+07,1.400000e+07,9.000000e+06,NaN,NaN
DepreciationIncomeStatement,7.000000e+06,NaN,NaN,NaN,9.000000e+06,NaN,NaN
ResearchAndDevelopment,1.590000e+08,1.230000e+08,2.530000e+08,1.920000e+08,1.890000e+08,NaN,NaN
SellingGeneralAndAdministration,1.240000e+08,1.210000e+08,1.830000e+08,1.250000e+08,1.280000e+08,NaN,NaN
SellingAndMarketingExpense,1.800000e+07,NaN,NaN,NaN,2.100000e+07,NaN,-39000000.0
GeneralAndAdministrativeExpense,1.060000e+08,1.210000e+08,1.620000e+08,1.250000e+08,1.070000e+08,NaN,NaN
OtherGandA,5.700000e+07,5.900000e+07,6.600000e+07,7.400000e+07,6.500000e+07,NaN,NaN
SalariesAndWages,4.900000e+07,6.200000e+07,9.600000e+07,5.100000e+07,4.200000e+07,NaN,NaN
GrossProfit,2.719000e+09,2.668000e+09,3.856000e+09,3.272000e+09,3.571000e+09,NaN,NaN
CostOfRevenue,6.085000e+09,5.451000e+09,6.268000e+09,6.281000e+09,6.349000e+09,NaN,NaN
TotalRevenue,8.804000e+09,8.119000e+09,1.012400e+10,9.553000e+09,9.920000e+09,NaN,NaN
OperatingRevenue,8.804000e+09,8.119000e+09,1.020900e+10,9.542000e+09,9.920000e+09,NaN,NaN

In [9]:
dre = pd.DataFrame(dre)
dre = dre/1000
dre = dre [dre.columns[::-1]]
dre

,2023-12-31,2024-03-31,2024-06-30,2024-09-30,2024-12-31,2025-03-31,2025-06-30
TaxEffectOfUnusualItems,NaN,NaN,6.664000e+04,8.661826e+04,-1.060544e+05,1.583456e+03,1.139000e+05
TaxRateForCalcs,NaN,NaN,3.400000e-04,1.232120e-04,3.218600e-05,3.166910e-04,3.400000e-04
NormalizedEBITDA,NaN,NaN,3.776000e+06,3.044000e+06,3.704000e+06,3.027000e+06,2.895000e+06
TotalUnusualItems,NaN,NaN,1.960000e+05,7.030000e+05,-3.295000e+06,5.000000e+03,3.350000e+05
TotalUnusualItemsExcludingGoodwill,NaN,NaN,1.960000e+05,7.030000e+05,-3.295000e+06,5.000000e+03,3.350000e+05
NetIncomeFromContinuingOperationNetMinorityInterest,NaN,NaN,2.769000e+06,2.412000e+06,-6.940000e+05,1.394000e+06,2.117000e+06
ReconciledDepreciation,NaN,NaN,7.930000e+05,7.480000e+05,8.020000e+05,7.040000e+05,7.800000e+05
ReconciledCostOfRevenue,NaN,NaN,5.565000e+06,5.547000e+06,5.489000e+06,4.771000e+06,5.312000e+06
EBITDA,NaN,NaN,3.972000e+06,3.747000e+06,4.090000e+05,3.032000e+06,3.230000e+06
EBIT,NaN,NaN,3.179000e+06,2.999000e+06,-3.930000e+05,2.328000e+06,2.450000e+06
NetInterestIncome,NaN,NaN,-5.280000e+05,-1.880000e+05,-6.160000e+05,-3.260000e+05,-4.090000e+05
InterestExpense,NaN,NaN,4.440000e+05,2.720000e+05,5.080000e+05,2.850000e+05,3.470000e+05
InterestIncome,NaN,NaN,7.800000e+04,4.300000e+04,2.000000e+04,5.600000e+04,1.120000e+05
NormalizedIncome,NaN,NaN,2.639640e+06,1.795618e+06,2.494946e+06,1.390583e+06,1.895900e+06
NetIncomeFromContinuingAndDiscontinuedOperation,NaN,NaN,2.769000e+06,2.412000e+06,-6.940000e+05,1.394000e+06,2.117000e+06
TotalExpenses,NaN,NaN,6.965000e+06,6.767000e+06,7.183000e+06,5.814000e+06,6.559000e+06
TotalOperatingIncomeAsReported,NaN,NaN,3.875000e+06,3.675000e+06,7.900000e+05,1.799000e+06,2.004000e+06
DilutedAverageShares,NaN,4.289631e+06,4.260000e+06,4.274508e+06,NaN,4.273772e+06,4.234000e+06
BasicAverageShares,NaN,4.285865e+06,4.260000e+06,4.269495e+06,NaN,4.268759e+06,4.234000e+06
DilutedEPS,NaN,3.900000e-04,6.500000e-04,5.600000e-04,NaN,3.300000e-04,5.000000e-04
BasicEPS,NaN,3.900000e-04,6.500000e-04,5.600000e-04,NaN,3.300000e-04,5.000000e-04
DilutedNIAvailtoComStockholders,NaN,NaN,2.769000e+06,2.412000e+06,-6.940000e+05,1.394000e+06,2.117000e+06
NetIncomeCommonStockholders,NaN,NaN,2.769000e+06,2.412000e+06,-6.940000e+05,1.394000e+06,2.117000e+06
NetIncome,NaN,NaN,2.769000e+06,2.412000e+06,-6.940000e+05,1.394000e+06,2.117000e+06
MinorityInterests,NaN,NaN,0.000000e+00,2.100000e+04,1.780000e+05,-2.000000e+03,-1.800000e+04
NetIncomeIncludingNoncontrollingInterests,NaN,NaN,2.769000e+06,2.391000e+06,-8.720000e+05,1.396000e+06,2.135000e+06
NetIncomeDiscontinuousOperations,0.0,NaN,NaN,NaN,NaN,NaN,NaN
NetIncomeContinuousOperations,NaN,NaN,2.769000e+06,2.391000e+06,-8.720000e+05,1.396000e+06,2.135000e+06
TaxProvision,NaN,NaN,-3.400000e+04,3.360000e+05,-2.900000e+04,6.470000e+05,-3.200000e+04
PretaxIncome,NaN,NaN,2.735000e+06,2.727000e+06,-9.010000e+05,2.043000e+06,2.103000e+06
OtherIncomeExpense,NaN,NaN,3.080000e+05,1.290000e+05,-3.226000e+06,6.400000e+04,2.670000e+05
SpecialIncomeCharges,NaN,NaN,9.200000e+05,8.390000e+05,-2.101000e+06,-5.060000e+05,-2.410000e+05
GainOnSaleOfBusiness,NaN,NaN,1.059000e+06,NaN,NaN,NaN,NaN
OtherSpecialCharges,NaN,NaN,9.000000e+04,3.050000e+05,2.540000e+05,2.530000e+05,1.090000e+05
WriteOff,NaN,6.000000e+03,-1.010000e+06,NaN,NaN,2.530000e+05,1.320000e+05
ImpairmentOfCapitalAssets,NaN,6.000000e+03,-1.010000e+06,-1.144000e+06,1.847000e+06,NaN,1.320000e+05
EarningsFromEquityInterest,NaN,NaN,1.120000e+05,-5.740000e+05,6.900000e+04,5.900000e+04,-6.800000e+04
GainOnSaleOfSecurity,NaN,NaN,-7.240000e+05,-1.360000e+05,-1.194000e+06,5.110000e+05,5.760000e+05
NetNonOperatingInterestIncomeExpense,NaN,NaN,-5.280000e+05,-1.880000e+05,-6.160000e+05,-3.260000e+05,-4.090000e+05
TotalOtherFinanceCost,NaN,NaN,1.620000e+05,-4.100000e+04,1.280000e+05,9.700000e+04,1.740000e+05
InterestExpenseNonOperating,NaN,NaN,4.440000e+05,2.720000e+05,5.080000e+05,2.850000e+05,3.470000e+05
InterestIncomeNonOperating,NaN,NaN,7.800000e+04,4.300000e+04,2.000000e+04,5.600000e+04,1.120000e+05
OperatingIncome,NaN,NaN,2.955000e+06,2.786000e+06,2.941000e+06,2.305000e+06,2.245000e+06
OperatingExpense,NaN,NaN,6.160000e+05,4.860000e+05,9.150000e+05,3.630000e+05,4.740000e+05
OtherOperatingExpenses,NaN,NaN,2.900000e+05,1.550000e+05,4.560000e+05,9.500000e+04,1.840000e+05
DepreciationAmortizationDepletionIncomeStatement,NaN,NaN,9.000000e+03,1.400000e+04,2.300000e+04,2.400000e+04,7.000000e+03
DepreciationAndAmortizationInIncomeStatement,NaN,NaN,9.000000e+03,1.400000e+04,2.300000e+04,2.400000e+04,7.000000e+03
DepreciationIncomeStatement,NaN,NaN,9.000000e+03,NaN,NaN,NaN,7.000000e+03
ResearchAndDevelopment,NaN,NaN,1.890000e+05,1.920000e+05,2.530000e+05,1.230000e+05,1.590000e+05
SellingGeneralAndAdministration,NaN,NaN,1.280000e+05,1.250000e+05,1.830000e+05,1.210000e+05,1.240000e+05
SellingAndMarketingExpense,-39000.0,NaN,2.100000e+04,NaN,NaN,NaN,1.800000e+04
GeneralAndAdministrativeExpense,NaN,NaN,1.070000e+05,1.250000e+05,1.620000e+05,1.210000e+05,1.060000e+05
OtherGandA,NaN,NaN,6.500000e+04,7.400000e+04,6.600000e+04,5.900000e+04,5.700000e+04
SalariesAndWages,NaN,NaN,4.200000e+04,5.100000e+04,9.600000e+04,6.200000e+04,4.900000e+04
GrossProfit,NaN,NaN,3.571000e+06,3.272000e+06,3.856000e+06,2.668000e+06,2.719000e+06
CostOfRevenue,NaN,NaN,6.349000e+06,6.281000e+06,6.268000e+06,5.451000e+06,6.085000e+06
TotalRevenue,NaN,NaN,9.920000e+06,9.553000e+06,1.012400e+07,8.119000e+06,8.804000e+06
OperatingRevenue,NaN,NaN,9.920000e+06,9.542000e+06,1.020900e+07,8.119000e+06,8.804000e+06

###Dados Anuais

In [11]:
bal = ativo.get_balance_sheet(freq='yearly')
bal

,2024-12-31,2023-12-31,2022-12-31,2021-12-31,2020-12-31
TreasurySharesNumber,2.702876e+08,2.391533e+08,2.958106e+08,2.928415e+08,NaN
OrdinarySharesNumber,4.268720e+09,4.299854e+09,4.483079e+09,4.839617e+09,NaN
ShareIssued,4.539008e+09,4.539008e+09,4.778889e+09,5.132458e+09,NaN
NetDebt,1.200600e+10,1.173600e+10,9.170000e+09,3.878000e+09,NaN
TotalDebt,1.767200e+10,1.679700e+10,1.543700e+10,1.720100e+10,NaN
...,...,...,...,...,...
AllowanceForDoubtfulAccountsReceivable,-5.200000e+07,-4.400000e+07,-4.300000e+07,-4.800000e+07,NaN
GrossAccountsReceivable,2.410000e+09,4.241000e+09,4.362000e+09,3.962000e+09,NaN
CashCashEquivalentsAndShortTermInvestments,5.006000e+09,3.660000e+09,4.797000e+09,1.190500e+10,NaN
OtherShortTermInvestments,5.300000e+07,5.100000e+07,6.100000e+07,1.840000e+08,NaN
CashAndCashEquivalents,4.953000e+09,3.609000e+09,4.736000e+09,1.172100e+10,NaN

In [13]:
balanco = pd.DataFrame(bal)
balanco = balanco/1000
balanco = balanco[balanco.columns[::-1]]
balanco

,2020-12-31,2021-12-31,2022-12-31,2023-12-31,2024-12-31
TreasurySharesNumber,NaN,2.928415e+05,2.958106e+05,239153.28,2.702876e+05
OrdinarySharesNumber,NaN,4.839617e+06,4.483079e+06,4299854.30,4.268720e+06
ShareIssued,NaN,5.132458e+06,4.778889e+06,4539007.58,4.539008e+06
NetDebt,NaN,3.878000e+06,9.170000e+06,11736000.00,1.200600e+07
TotalDebt,NaN,1.720100e+07,1.543700e+07,16797000.00,1.767200e+07
...,...,...,...,...,...
AllowanceForDoubtfulAccountsReceivable,NaN,-4.800000e+04,-4.300000e+04,-44000.00,-5.200000e+04
GrossAccountsReceivable,NaN,3.962000e+06,4.362000e+06,4241000.00,2.410000e+06
CashCashEquivalentsAndShortTermInvestments,NaN,1.190500e+07,4.797000e+06,3660000.00,5.006000e+06
OtherShortTermInvestments,NaN,1.840000e+05,6.100000e+04,51000.00,5.300000e+04
CashAndCashEquivalents,NaN,1.172100e+07,4.736000e+06,3609000.00,4.953000e+06

### Avaliação Fundamentalista

In [14]:
fig = make_subplots(rows=2,
                    cols=2,
                    row_heights=[5,5],
                    column_widths=[3,3],
                    subplot_titles=('EBITDA','Lucro Líquido', 'Dívida Líquida', 'Dívida Total'),
                    shared_xaxes=False)
fig.add_trace(go.Bar(name='EBTIDA',x=dre.columns, y=dre.loc['EBITDA']), row=1, col=1)
fig.add_trace(go.Bar(name='Lucro Líquido',x=dre.columns, y=dre.loc['NetIncome']), row=1, col=2)

fig.add_trace(go.Bar(name='Dívida Líquida',x=balanco.columns, y=balanco.loc['NetDebt']), row=2, col=1)
fig.add_trace(go.Bar(name='Dívida Total',x=balanco.columns, y=balanco.loc['TotalDebt']), row=2, col=2)
fig.update_layout(title_text='<b>Avaliação Fundamentalista <b>',
                    template= 'plotly_dark', #template pré-definido da plotly
                    showlegend=False, #esconder ou mostrar legenda
                  height=500, #altura
                  width=800) #largura

fig.show()